print ('Author:AntonnetteSwaby')
print ('Date:3/5/2022')
print ('Course: ITT103')
print ('Purpose: The Commission rate is based on two factors,the amount of sales and the class to which a salesperson belongs.')

print ('START')
print ('DECLARE') 
print ('sales amount Real')
print ('sales number Interger')
print ('sales class Interger')
print ('Nest IFs to calculate commission')
print ('While sales person''Do')
print ('IF class==1:')
print ('IF sales=<1000')
print ('Rate=0.06')
print ('commision=sale amount * 0.06')
print ('IF sales > 100 but < 2000')
print ('Rate=0.07')
print ('IF sales 2000 >')
print ('Rate=0.1')
print ('IF class==2:')
print ('IF sales < 1000')
print ('Rate=0.04')
print ('commission=sales amount * 0.04')
print ('IF sales 1000 >')
print ('Rate=0.06')
print ('commission=sales amount * 0.06')
print ('IF class==3:')
print ('Rate=0.045')
print ('If class<1 or class>3:')
print('Error message')
print ('commission received by sales person')
print('ENDIF')
print('ENDIF')
print('END')
